name: Deploy Docker image to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: docker pull hello-world:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-container-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: hello-world:latest
        container-command: "python app.py"  # Adjust this according to your application startup command
